############
## Queue Group Configuration. The queue stats will be grouped by the 'groupName'
## if the 'queueNameRegex' matches the name of the Queue.

## groupName            The stats from Queues matched by the 'queueNameRegex' will be reported under this name
## queueNameRegex       A Regex to match the Queue Name
## showIndividualStats  If set to false then the Individual Queue stats will not be reported.
##                      This will help if there are several short lived queues and an explosion of metrics
##                      in the controller can be avoided
############

# Uncomment the following lines for configuration
queueGroups:
- groupName: group1
  queueNameRegex: queue.+
  showIndividualStats: false

# Queue Group Configuration
#- groupName: group2
#  queueNameRegex: temp.+
#  showIndividualStats: false

excludeQueueRegex: ^[0-9]*

encryptionKey: "myKey"

servers:

   - host: "localhost"
     port: 15672
     useSSL: false
     username: "guest"
     password: "guest"
     encryptedPassword: ""
     connectTimeout: 10000
     socketTimeout: 10000
     displayName : "Server2"

# number of concurrent tasks
numberOfThreads: 5

dictionary:
  ack: "Acknowledged"
  deliver: "Delivered"
  deliver_get: "Delivered (Total)"
  deliver_no_ack: "Delivered No-Ack"
  get: "Got"
  get_no_ack: "Got No-Ack"
  publish: "Published"
  redeliver: "Redelivered"
  messages_ready: "Available"
  messages_unacknowledged: "Pending Acknowledgements"
  consumers: "Count"
  active_consumers: "Active"
  idle_consumers: "Idle"
  slave_nodes: "Slaves Count"
  synchronised_slave_nodes: "Synchronized Slaves Count"
  down_slave_nodes: "Down Slaves Count"
  messages: "Messages"

metrics:
     #Items in Nodes|<node>|Messages - data looked up from /api/channels
   - channelNodeMsgProps:
         - name: "ack"
           metricType: "OBS.CUR.COL"
           collectDelta: "true"
         - name: "deliver"
           metricType: "OBS.CUR.COL"
           collectDelta: "true"
         - name: "deliver_no_ack"
           metricType: "OBS.CUR.COL"
           collectDelta: "true"
         - name: "get_no_ack"
           metricType: "OBS.CUR.COL"
           collectDelta: "true"
         - name: "publish"
           metricType: "OBS.CUR.COL"
           collectDelta: "true"
         - name: "redeliver"
           metricType: "OBS.CUR.COL"
           collectDelta: "true"
     #Queue Group data, stats combined by groupName defined in queueGroups above
   - queueGroupProps:
         - name: "consumers"
           metricType: "OBS.CUR.COL"
           collectDelta: "true"
     #Items in Nodes|<node>|Messages - data looked up from /api/queues
   - queueNodeMsgProps:
         - name: "messages_ready"
           metricType: "OBS.CUR.COL"
           collectDelta: "true"
         - name: "messages_unacknowledged"
           metricType: "OBS.CUR.COL"
           collectDelta: "true"
     #Items in Nodes|<node>|Consumers - data looked up from /api/queues
   - queueNodeProps:
         - name: "consumers"
           metricType: "OBS.CUR.COL"
           collectDelta: "true"
     #Items in Queues|<host>|<QName>|Messages - data looked up from /api/queues
   - queueMessageProps:
         - name: "messages_ready"
           metricType: "OBS.CUR.COL"
           collectDelta: "true"
         - name: "messages_unacknowledged"
           metricType: "OBS.CUR.COL"
           collectDelta: "true"
     #Items in Queues|<host>|<QName>|Replication - data looked up from /api/queues
   - queueReplicationCountsProps:
         - name: "slave_nodes"
           metricType: "OBS.CUR.COL"
           collectDelta: "true"
         - name: "synchronised_slave_nodes"
           metricType: "OBS.CUR.COL"
           collectDelta: "true"
         - name: "down_slave_nodes"
           metricType: "OBS.CUR.COL"
           collectDelta: "true"
     #Items in Queues|<host>|<QName>|Messages - data looked up from /api/queues/message_stats
   - queueMessageStatsProps:
         - name: "ack"
           metricType: "OBS.CUR.COL"
           collectDelta: "true"
         - name: "deliver_get"
           metricType: "OBS.CUR.COL"
           collectDelta: "true"
         - name: "deliver"
           metricType: "OBS.CUR.COL"
           collectDelta: "true"
         - name: "deliver_no_ack"
           metricType: "OBS.CUR.COL"
           collectDelta: "true"
         - name: "get"
           metricType: "OBS.CUR.COL"
           collectDelta: "true"
         - name: "get_no_ack"
           metricType: "OBS.CUR.COL"
           collectDelta: "true"
         - name: "publish"
           metricType: "OBS.CUR.COL"
           collectDelta: "true"
         - name: "redeliver"
           metricType: "OBS.CUR.COL"
           collectDelta: "true"
     #Items in Summary|Messages - data looked up from /api/queues
   - queueSummaryProps:
         - name: "messages_ready"
           metricType: "OBS.CUR.COL"
           collectDelta: "true"
         - name: "deliver_get"
           metricType: "OBS.CUR.COL"
           collectDelta: "true"
         - name: "publish"
           metricType: "OBS.CUR.COL"
           collectDelta: "true"
         - name: "redeliver"
           metricType: "OBS.CUR.COL"
           collectDelta: "true"
         - name: "messages_unacknowledged"
           metricType: "OBS.CUR.COL"
           collectDelta: "true"
     #Items in Clusters|<Cluster>|Queues - data looked up from /api/overview
   - queueTotalsProps:
         - name: "messages"
           metricType: "OBS.CUR.COL"
           collectDelta: "true"
         - name: "messages_ready"
           metricType: "OBS.CUR.COL"
           collectDelta: "true"
         - name: "messages_unacknowledged"
           metricType: "OBS.CUR.COL"
           collectDelta: "true"
     #Items in Clusters|<Cluster>|Messages - data looked up from /api/overview
   - messageTotalsProps:
         - name: "publish"
           metricType: "OBS.CUR.COL"
           collectDelta: "true"
         - name: "deliver_get"
           metricType: "OBS.CUR.COL"
           collectDelta: "true"
         - name: "confirm"
           metricType: "OBS.CUR.COL"
           collectDelta: "true"
         - name: "get"
           metricType: "OBS.CUR.COL"
           collectDelta: "true"
     #Items in Clusters|<Cluster>|Objects - data looked up from /api/overview
   - objectTotalsProps:
         - name: "consumers"
           metricType: "OBS.CUR.COL"
           collectDelta: "true"
         - name: "queues"
           metricType: "OBS.CUR.COL"
           collectDelta: "true"
         - name: "exchanges"
           metricType: "OBS.CUR.COL"
           collectDelta: "true"
         - name: "connections"
           metricType: "OBS.CUR.COL"
           collectDelta: "true"
         - name: "channels"
           metricType: "OBS.CUR.COL"
           collectDelta: "true"
   #Items in Nodes|<node> - data looked up from /api/nodes
   - nodeDataMetrics:
         - name: "proc_used"
           metricType: "OBS.CUR.COL"
           collectDelta: "true"
           prefix: "|Erlang Processes"
         - name: "disk_free_alarm"
           metricType: "OBS.CUR.COL"
           collectDelta: "true"
           isBoolean: "true"
           prefix: "|Disk Free Alarm Activated"
         - name: "mem_alarm"
           metricType: "OBS.CUR.COL"
           collectDelta: "true"
           isBoolean: "true"
           prefix: "|Memory Free Alarm Activated"
         - name: "fd_used"
           metricType: "OBS.CUR.COL"
           collectDelta: "true"
           prefix: "|File Descriptors"
         - name: "mem_used"
           metricType: "OBS.CUR.COL"
           collectDelta: "true"
           divisor: "1048576"
           prefix: "|Memory(MB)"
         - name: "sockets_used"
           metricType: "OBS.CUR.COL"
           collectDelta: "true"
           prefix: "|Sockets"
         - name: "channels_count"
           metricType: "OBS.CUR.COL"
           collectDelta: "true"
           prefix: "|Channels|Count"
         - name: "channels_blocked"
           metricType: "OBS.CUR.COL"
           collectDelta: "true"
           prefix: "|Channels|Blocked"
         - name: "summary_channels"
           metricType: "OBS.CUR.COL"
           collectDelta: "true"
           prefix: "|Summary|Channels"
         - name: "consumers"
           metricType: "OBS.CUR.COL"
           collectDelta: "true"
           prefix: "|Summary|Consumers"
     #Per Minute Metrics, All these metric suffixes will be reported as per minute also
   - perMinMetricSuffixes:
         - name: "|Messages|Delivered (Total)"
           metricType: "OBS.CUR.COL"
           collectDelta: "false"
         - name: "|Messages|Published"
           metricType: "OBS.CUR.COL"
           collectDelta: "false"
         - name: "|Messages|Acknowledged"
           metricType: "OBS.CUR.COL"
           collectDelta: "false"
         - name: "|Messages|Redelivered"
           metricType: "OBS.CUR.COL"
           collectDelta: "false"

#This will create this metric in all the tiers, under this path
metricPrefix: Custom Metrics | RabbitMQ |

#This will create it in specific Tier/Component. Make sure to replace <COMPONENT_ID> with the appropriate one from your environment.
#To find the <COMPONENT_ID> in your environment, please follow the screenshot https://docs.appdynamics.com/display/PRO42/Build+a+Monitoring+Extension+Using+Java
#metricPrefix: Server|Component:<COMPONENT_ID>|Custom Metrics|RabbitMQ|
